In [1]:
%matplotlib inline
import pandas as pd
import sklearn.linear_model as lm
import matplotlib.pyplot as plt
import seaborn as sns

In [85]:
df = pd.read_csv('../data/flight_delays.csv')
df = df[df.DEP_DEL15.notnull()]

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 458311 entries, 0 to 469967
Data columns (total 15 columns):
DAY_OF_MONTH             458311 non-null int64
DAY_OF_WEEK              458311 non-null int64
FL_DATE                  458311 non-null object
UNIQUE_CARRIER           458311 non-null object
AIRLINE_ID               458311 non-null int64
CARRIER                  458311 non-null object
ORIGIN_AIRPORT_ID        458311 non-null int64
ORIGIN_AIRPORT_SEQ_ID    458311 non-null int64
ORIGIN_CITY_MARKET_ID    458311 non-null int64
DEST_AIRPORT_ID          458311 non-null int64
DEST_AIRPORT_SEQ_ID      458311 non-null int64
DEST_CITY_MARKET_ID      458311 non-null int64
CRS_DEP_TIME             458311 non-null int64
DEP_TIME                 458311 non-null float64
DEP_DEL15                458311 non-null float64
dtypes: float64(2), int64(10), object(3)
memory usage: 55.9+ MB

In [87]:
df.head()

,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,UNIQUE_CARRIER,AIRLINE_ID,CARRIER,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,CRS_DEP_TIME,DEP_TIME,DEP_DEL15
0,1,4,2015-01-01,AA,19805,AA,12478,1247802,31703,12892,1289203,32575,900,855.0,0.0
1,1,4,2015-01-01,AA,19805,AA,12892,1289203,32575,12478,1247802,31703,900,856.0,0.0
2,1,4,2015-01-01,AA,19805,AA,12478,1247802,31703,12892,1289203,32575,1230,1226.0,0.0
3,1,4,2015-01-01,AA,19805,AA,12892,1289203,32575,12478,1247802,31703,1220,1214.0,0.0
4,1,4,2015-01-01,AA,19805,AA,11298,1129803,30194,12173,1217302,32134,1305,1754.0,1.0

In [88]:
df_new = pd.get_dummies(df, columns=['CARRIER','DEST_AIRPORT_ID'], drop_first=True)

In [89]:
df_new.head()

,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,UNIQUE_CARRIER,AIRLINE_ID,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,...,DEST_AIRPORT_ID_15411,DEST_AIRPORT_ID_15412,DEST_AIRPORT_ID_15497,DEST_AIRPORT_ID_15582,DEST_AIRPORT_ID_15607,DEST_AIRPORT_ID_15624,DEST_AIRPORT_ID_15841,DEST_AIRPORT_ID_15919,DEST_AIRPORT_ID_15991,DEST_AIRPORT_ID_16218
0,1,4,2015-01-01,AA,19805,12478,1247802,31703,1289203,32575,...,0,0,0,0,0,0,0,0,0,0
1,1,4,2015-01-01,AA,19805,12892,1289203,32575,1247802,31703,...,0,0,0,0,0,0,0,0,0,0
2,1,4,2015-01-01,AA,19805,12478,1247802,31703,1289203,32575,...,0,0,0,0,0,0,0,0,0,0
3,1,4,2015-01-01,AA,19805,12892,1289203,32575,1247802,31703,...,0,0,0,0,0,0,0,0,0,0
4,1,4,2015-01-01,AA,19805,11298,1129803,30194,1217302,32134,...,0,0,0,0,0,0,0,0,0,0

In [90]:
features = [i for i in df_new.columns if i.startswith('DEST_AIRPORT_ID')]
features += ['CRS_DEP_TIME']
features

['DEST_AIRPORT_ID_10136',
 'DEST_AIRPORT_ID_10140',
 'DEST_AIRPORT_ID_10141',
 'DEST_AIRPORT_ID_10146',
 'DEST_AIRPORT_ID_10155',
 'DEST_AIRPORT_ID_10157',
 'DEST_AIRPORT_ID_10158',
 'DEST_AIRPORT_ID_10165',
 'DEST_AIRPORT_ID_10170',
 'DEST_AIRPORT_ID_10185',
 'DEST_AIRPORT_ID_10208',
 'DEST_AIRPORT_ID_10257',
 'DEST_AIRPORT_ID_10268',
 'DEST_AIRPORT_ID_10279',
 'DEST_AIRPORT_ID_10299',
 'DEST_AIRPORT_ID_10333',
 'DEST_AIRPORT_ID_10372',
 'DEST_AIRPORT_ID_10397',
 'DEST_AIRPORT_ID_10408',
 'DEST_AIRPORT_ID_10423',
 'DEST_AIRPORT_ID_10431',
 'DEST_AIRPORT_ID_10434',
 'DEST_AIRPORT_ID_10469',
 'DEST_AIRPORT_ID_10529',
 'DEST_AIRPORT_ID_10551',
 'DEST_AIRPORT_ID_10561',
 'DEST_AIRPORT_ID_10599',
 'DEST_AIRPORT_ID_10620',
 'DEST_AIRPORT_ID_10627',
 'DEST_AIRPORT_ID_10631',
 'DEST_AIRPORT_ID_10666',
 'DEST_AIRPORT_ID_10685',
 'DEST_AIRPORT_ID_10693',
 'DEST_AIRPORT_ID_10713',
 'DEST_AIRPORT_ID_10721',
 'DEST_AIRPORT_ID_10728',
 'DEST_AIRPORT_ID_10731',
 'DEST_AIRPORT_ID_10732',
 'DEST_AIRPORT_ID_10739',
 'DEST_AIRPORT_ID_10747',
 'DEST_AIRPORT_ID_10754',
 'DEST_AIRPORT_ID_10779',
 'DEST_AIRPORT_ID_10781',
 'DEST_AIRPORT_ID_10785',
 'DEST_AIRPORT_ID_10792',
 'DEST_AIRPORT_ID_10800',
 'DEST_AIRPORT_ID_10821',
 'DEST_AIRPORT_ID_10849',
 'DEST_AIRPORT_ID_10868',
 'DEST_AIRPORT_ID_10874',
 'DEST_AIRPORT_ID_10918',
 'DEST_AIRPORT_ID_10926',
 'DEST_AIRPORT_ID_10930',
 'DEST_AIRPORT_ID_10980',
 'DEST_AIRPORT_ID_10990',
 'DEST_AIRPORT_ID_10994',
 'DEST_AIRPORT_ID_11003',
 'DEST_AIRPORT_ID_11013',
 'DEST_AIRPORT_ID_11041',
 'DEST_AIRPORT_ID_11042',
 'DEST_AIRPORT_ID_11049',
 'DEST_AIRPORT_ID_11057',
 'DEST_AIRPORT_ID_11066',
 'DEST_AIRPORT_ID_11067',
 'DEST_AIRPORT_ID_11076',
 'DEST_AIRPORT_ID_11092',
 'DEST_AIRPORT_ID_11097',
 'DEST_AIRPORT_ID_11109',
 'DEST_AIRPORT_ID_11111',
 'DEST_AIRPORT_ID_11122',
 'DEST_AIRPORT_ID_11140',
 'DEST_AIRPORT_ID_11146',
 'DEST_AIRPORT_ID_11150',
 'DEST_AIRPORT_ID_11193',
 'DEST_AIRPORT_ID_11203',
 'DEST_AIRPORT_ID_11252',
 'DEST_AIRPORT_ID_11259',
 'DEST_AIRPORT_ID_11267',
 'DEST_AIRPORT_ID_11274',
 'DEST_AIRPORT_ID_11278',
 'DEST_AIRPORT_ID_11292',
 'DEST_AIRPORT_ID_11298',
 'DEST_AIRPORT_ID_11308',
 'DEST_AIRPORT_ID_11315',
 'DEST_AIRPORT_ID_11337',
 'DEST_AIRPORT_ID_11413',
 'DEST_AIRPORT_ID_11423',
 'DEST_AIRPORT_ID_11433',
 'DEST_AIRPORT_ID_11447',
 'DEST_AIRPORT_ID_11471',
 'DEST_AIRPORT_ID_11481',
 'DEST_AIRPORT_ID_11503',
 'DEST_AIRPORT_ID_11525',
 'DEST_AIRPORT_ID_11537',
 'DEST_AIRPORT_ID_11540',
 'DEST_AIRPORT_ID_11577',
 'DEST_AIRPORT_ID_11587',
 'DEST_AIRPORT_ID_11603',
 'DEST_AIRPORT_ID_11612',
 'DEST_AIRPORT_ID_11617',
 'DEST_AIRPORT_ID_11618',
 'DEST_AIRPORT_ID_11624',
 'DEST_AIRPORT_ID_11630',
 'DEST_AIRPORT_ID_11637',
 'DEST_AIRPORT_ID_11638',
 'DEST_AIRPORT_ID_11641',
 'DEST_AIRPORT_ID_11648',
 'DEST_AIRPORT_ID_11695',
 'DEST_AIRPORT_ID_11697',
 'DEST_AIRPORT_ID_11721',
 'DEST_AIRPORT_ID_11775',
 'DEST_AIRPORT_ID_11778',
 'DEST_AIRPORT_ID_11823',
 'DEST_AIRPORT_ID_11865',
 'DEST_AIRPORT_ID_11867',
 'DEST_AIRPORT_ID_11884',
 'DEST_AIRPORT_ID_11898',
 'DEST_AIRPORT_ID_11905',
 'DEST_AIRPORT_ID_11921',
 'DEST_AIRPORT_ID_11953',
 'DEST_AIRPORT_ID_11973',
 'DEST_AIRPORT_ID_11977',
 'DEST_AIRPORT_ID_11980',
 'DEST_AIRPORT_ID_11982',
 'DEST_AIRPORT_ID_11986',
 'DEST_AIRPORT_ID_11995',
 'DEST_AIRPORT_ID_11996',
 'DEST_AIRPORT_ID_12003',
 'DEST_AIRPORT_ID_12007',
 'DEST_AIRPORT_ID_12012',
 'DEST_AIRPORT_ID_12016',
 'DEST_AIRPORT_ID_12094',
 'DEST_AIRPORT_ID_12129',
 'DEST_AIRPORT_ID_12156',
 'DEST_AIRPORT_ID_12173',
 'DEST_AIRPORT_ID_12177',
 'DEST_AIRPORT_ID_12191',
 'DEST_AIRPORT_ID_12197',
 'DEST_AIRPORT_ID_12206',
 'DEST_AIRPORT_ID_12217',
 'DEST_AIRPORT_ID_12255',
 'DEST_AIRPORT_ID_12264',
 'DEST_AIRPORT_ID_12265',
 'DEST_AIRPORT_ID_12266',
 'DEST_AIRPORT_ID_12278',
 'DEST_AIRPORT_ID_12280',
 'DEST_AIRPORT_ID_12320',
 'DEST_AIRPORT_ID_12323',
 'DEST_AIRPORT_ID_12335',
 'DEST_AIRPORT_ID_12339',
 'DEST_AIRPORT_ID_12343',
 'DEST_AIRPORT_ID_12389',
 'DEST_AIRPORT_ID_12391',
 'DEST_AIRPORT_ID_12402',
 'DEST_AIRPORT_ID_12441',
 'DEST_AIRPORT_ID_12448',
 'DEST_AIRPORT_ID_12451',
 'DEST_AIRPORT_ID_12478',
 'DEST_AIRPORT_ID_12511',
 'DEST_AIRPORT_ID_12519',
 'DEST_AIRPORT_ID_12523',
 'DEST_AIRPORT_ID_12758',
 'DEST_AIRPORT_ID_12819',
 'DEST_AIRPORT_ID_12884',
 'DEST_AIRPORT_ID_12888',
 'DEST_AIRPORT_ID_12889',
 'DEST_AIRPORT_ID_12891',
 'DEST_AIRPORT_ID_12892',
 'DEST_AIRPORT_ID_12896',
 'DEST_AIRPORT_ID_12898',
 'DEST_AIRPORT_ID_12915',
 'DEST_AIRPORT_ID_12945',
 'DEST_AIRPORT_ID_12951',
 'DEST_AIRPORT_ID_12953',
 'DEST_AIRPORT_ID_12954',
 'DEST_AIRPORT_ID_12982',
 'DEST_AIRPORT_ID_12992',
 'DEST_AIRPORT_ID_13029',
 'DEST_AIRPORT_ID_13061',
 'DEST_AIRPORT_ID_13076',
 'DEST_AIRPORT_ID_13127',
 'DEST_AIRPORT_ID_13158',
 'DEST_AIRPORT_ID_13184',
 'DEST_AIRPORT_ID_13198',
 'DEST_AIRPORT_ID_13204',
 'DEST_AIRPORT_ID_13230',
 'DEST_AIRPORT_ID_13232',
 'DEST_AIRPORT_ID_13241',
 'DEST_AIRPORT_ID_13244',
 'DEST_AIRPORT_ID_13256',
 'DEST_AIRPORT_ID_13264',
 'DEST_AIRPORT_ID_13277',
 'DEST_AIRPORT_ID_13290',
 'DEST_AIRPORT_ID_13296',
 'DEST_AIRPORT_ID_13303',
 'DEST_AIRPORT_ID_13342',
 'DEST_AIRPORT_ID_13344',
 'DEST_AIRPORT_ID_13360',
 'DEST_AIRPORT_ID_13367',
 'DEST_AIRPORT_ID_13377',
 'DEST_AIRPORT_ID_13388',
 'DEST_AIRPORT_ID_13422',
 'DEST_AIRPORT_ID_13433',
 'DEST_AIRPORT_ID_13459',
 'DEST_AIRPORT_ID_13476',
 'DEST_AIRPORT_ID_13485',
 'DEST_AIRPORT_ID_13486',
 'DEST_AIRPORT_ID_13487',
 'DEST_AIRPORT_ID_13495',
 'DEST_AIRPORT_ID_13502',
 'DEST_AIRPORT_ID_13577',
 'DEST_AIRPORT_ID_13795',
 'DEST_AIRPORT_ID_13796',
 'DEST_AIRPORT_ID_13830',
 'DEST_AIRPORT_ID_13851',
 'DEST_AIRPORT_ID_13871',
 'DEST_AIRPORT_ID_13873',
 'DEST_AIRPORT_ID_13891',
 'DEST_AIRPORT_ID_13930',
 'DEST_AIRPORT_ID_13931',
 'DEST_AIRPORT_ID_13933',
 'DEST_AIRPORT_ID_13964',
 'DEST_AIRPORT_ID_13970',
 'DEST_AIRPORT_ID_14006',
 'DEST_AIRPORT_ID_14025',
 'DEST_AIRPORT_ID_14027',
 'DEST_AIRPORT_ID_14057',
 'DEST_AIRPORT_ID_14098',
 'DEST_AIRPORT_ID_14100',
 'DEST_AIRPORT_ID_14107',
 'DEST_AIRPORT_ID_14108',
 'DEST_AIRPORT_ID_14109',
 'DEST_AIRPORT_ID_14113',
 'DEST_AIRPORT_ID_14122',
 'DEST_AIRPORT_ID_14150',
 'DEST_AIRPORT_ID_14193',
 'DEST_AIRPORT_ID_14222',
 'DEST_AIRPORT_ID_14252',
 'DEST_AIRPORT_ID_14254',
 'DEST_AIRPORT_ID_14256',
 'DEST_AIRPORT_ID_14262',
 'DEST_AIRPORT_ID_14288',
 'DEST_AIRPORT_ID_14307',
 'DEST_AIRPORT_ID_14321',
 'DEST_AIRPORT_ID_14457',
 'DEST_AIRPORT_ID_14487',
 'DEST_AIRPORT_ID_14489',
 'DEST_AIRPORT_ID_14492',
 'DEST_AIRPORT_ID_14520',
 'DEST_AIRPORT_ID_14524',
 'DEST_AIRPORT_ID_14543',
 'DEST_AIRPORT_ID_14570',
 'DEST_AIRPORT_ID_14574',
 'DEST_AIRPORT_ID_14576',
 'DEST_AIRPORT_ID_14588',
 'DEST_AIRPORT_ID_14633',
 'DEST_AIRPORT_ID_14635',
 'DEST_AIRPORT_ID_14674',
 'DEST_AIRPORT_ID_14679',
 'DEST_AIRPORT_ID_14683',
 'DEST_AIRPORT_ID_14685',
 'DEST_AIRPORT_ID_14689',
 'DEST_AIRPORT_ID_14696',
 'DEST_AIRPORT_ID_14698',
 'DEST_AIRPORT_ID_14709',
 'DEST_AIRPORT_ID_14711',
 'DEST_AIRPORT_ID_14730',
 'DEST_AIRPORT_ID_14747',
 'DEST_AIRPORT_ID_14771',
 'DEST_AIRPORT_ID_14783',
 'DEST_AIRPORT_ID_14794',
 'DEST_AIRPORT_ID_14814',
 'DEST_AIRPORT_ID_14828',
 'DEST_AIRPORT_ID_14831',
 'DEST_AIRPORT_ID_14842',
 'DEST_AIRPORT_ID_14843',
 'DEST_AIRPORT_ID_14869',
 'DEST_AIRPORT_ID_14893',
 'DEST_AIRPORT_ID_14905',
 'DEST_AIRPORT_ID_14908',
 'DEST_AIRPORT_ID_14952',
 'DEST_AIRPORT_ID_14960',
 'DEST_AIRPORT_ID_14986',
 'DEST_AIRPORT_ID_15008',
 'DEST_AIRPORT_ID_15016',
 'DEST_AIRPORT_ID_15024',
 'DEST_AIRPORT_ID_15027',
 'DEST_AIRPORT_ID_15041',
 'DEST_AIRPORT_ID_15048',
 'DEST_AIRPORT_ID_15070',
 'DEST_AIRPORT_ID_15096',
 'DEST_AIRPORT_ID_15249',
 'DEST_AIRPORT_ID_15295',
 'DEST_AIRPORT_ID_15304',
 'DEST_AIRPORT_ID_15323',
 'DEST_AIRPORT_ID_15356',
 'DEST_AIRPORT_ID_15370',
 'DEST_AIRPORT_ID_15376',
 'DEST_AIRPORT_ID_15380',
 'DEST_AIRPORT_ID_15389',
 'DEST_AIRPORT_ID_15401',
 'DEST_AIRPORT_ID_15411',
 'DEST_AIRPORT_ID_15412',
 'DEST_AIRPORT_ID_15497',
 'DEST_AIRPORT_ID_15582',
 'DEST_AIRPORT_ID_15607',
 'DEST_AIRPORT_ID_15624',
 'DEST_AIRPORT_ID_15841',
 'DEST_AIRPORT_ID_15919',
 'DEST_AIRPORT_ID_15991',
 'DEST_AIRPORT_ID_16218',
 'CRS_DEP_TIME']

In [91]:
df_new[features]

,DEST_AIRPORT_ID_10136,DEST_AIRPORT_ID_10140,DEST_AIRPORT_ID_10141,DEST_AIRPORT_ID_10146,DEST_AIRPORT_ID_10155,DEST_AIRPORT_ID_10157,DEST_AIRPORT_ID_10158,DEST_AIRPORT_ID_10165,DEST_AIRPORT_ID_10170,DEST_AIRPORT_ID_10185,...,DEST_AIRPORT_ID_15412,DEST_AIRPORT_ID_15497,DEST_AIRPORT_ID_15582,DEST_AIRPORT_ID_15607,DEST_AIRPORT_ID_15624,DEST_AIRPORT_ID_15841,DEST_AIRPORT_ID_15919,DEST_AIRPORT_ID_15991,DEST_AIRPORT_ID_16218,CRS_DEP_TIME
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,900
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,900
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1230
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1220
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1305
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1215
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1745
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,700
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2150
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1115
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2300
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,800
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1245
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,700
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1100
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1500
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1845
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1515
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,755
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1050
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,720
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,900
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1850
24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1500
26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1225
27,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2330
28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,805
29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1415
30,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1955
31,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1445
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
469938,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1010
469939,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1915
469940,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,940
469941,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1455
469942,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,900
469943,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1125
469944,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1105
469945,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1825
469946,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1050
469947,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,920
469948,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1730
469949,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1715
469950,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,800
469951,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,705
469952,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,935
469953,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1305
469954,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,625
469955,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1710
469956,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,745
469957,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1550
469958,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1040
469959,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1120
469960,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1510
469961,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,725
469962,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1305
469963,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1145
469964,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1805
469965,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,710
469966,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,755
469967,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,815

In [93]:
model = lm.LogisticRegression()
model.fit(df_new[features], df_new['DEP_DEL15'])

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [94]:
from sklearn import metrics

In [102]:
auc = metrics.roc_auc_score(df_new.DEP_DEL15, model.predict_proba(df_new[features]).T[0])
auc

0.37489887411852474

In [103]:
preds = pd.Series(model.predict_proba(df_new[features]).T[0])
df_new['Predictions'] = preds

In [104]:
df_new

,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,UNIQUE_CARRIER,AIRLINE_ID,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,...,DEST_AIRPORT_ID_15412,DEST_AIRPORT_ID_15497,DEST_AIRPORT_ID_15582,DEST_AIRPORT_ID_15607,DEST_AIRPORT_ID_15624,DEST_AIRPORT_ID_15841,DEST_AIRPORT_ID_15919,DEST_AIRPORT_ID_15991,DEST_AIRPORT_ID_16218,Predictions
0,1,4,2015-01-01,AA,19805,12478,1247802,31703,1289203,32575,...,0,0,0,0,0,0,0,0,0,0.857981
1,1,4,2015-01-01,AA,19805,12892,1289203,32575,1247802,31703,...,0,0,0,0,0,0,0,0,0,0.844365
2,1,4,2015-01-01,AA,19805,12478,1247802,31703,1289203,32575,...,0,0,0,0,0,0,0,0,0,0.826796
3,1,4,2015-01-01,AA,19805,12892,1289203,32575,1247802,31703,...,0,0,0,0,0,0,0,0,0,0.811942
4,1,4,2015-01-01,AA,19805,11298,1129803,30194,1217302,32134,...,0,0,0,0,0,0,0,0,0,0.828328
6,1,4,2015-01-01,AA,19805,11298,1129803,30194,1383002,33830,...,0,0,0,0,0,0,0,0,0,0.729514
7,1,4,2015-01-01,AA,19805,12173,1217302,32134,1129803,30194,...,0,0,0,0,0,0,0,0,0,0.874502
8,1,4,2015-01-01,AA,19805,12478,1247802,31703,1289203,32575,...,0,0,0,0,0,0,0,0,0,0.689740
9,1,4,2015-01-01,AA,19805,12892,1289203,32575,1247802,31703,...,0,0,0,0,0,0,0,0,0,0.823118
10,1,4,2015-01-01,AA,19805,12892,1289203,32575,1247802,31703,...,0,0,0,0,0,0,0,0,0,0.689843
11,1,4,2015-01-01,AA,19805,13830,1383002,33830,1289203,32575,...,0,0,0,0,0,0,0,0,0,0.805242
12,1,4,2015-01-01,AA,19805,12478,1247802,31703,1477101,32457,...,0,0,0,0,0,0,0,0,0,0.809202
13,1,4,2015-01-01,AA,19805,14771,1477101,32457,1247802,31703,...,0,0,0,0,0,0,0,0,0,0.868441
14,1,4,2015-01-01,AA,19805,10397,1039705,30397,1330303,32467,...,0,0,0,0,0,0,0,0,0,0.839683
15,1,4,2015-01-01,AA,19805,12478,1247802,31703,1289203,32575,...,0,0,0,0,0,0,0,0,0,0.779513
16,1,4,2015-01-01,AA,19805,14771,1477101,32457,1247802,31703,...,0,0,0,0,0,0,0,0,0,0.754755
17,1,4,2015-01-01,AA,19805,12478,1247802,31703,1289203,32575,...,0,0,0,0,0,0,0,0,0,0.777667
18,1,4,2015-01-01,AA,19805,12892,1289203,32575,1247802,31703,...,0,0,0,0,0,0,0,0,0,0.810230
19,1,4,2015-01-01,AA,19805,11298,1129803,30194,1477101,32457,...,0,0,0,0,0,0,0,0,0,0.815809
20,1,4,2015-01-01,AA,19805,14771,1477101,32457,1129803,30194,...,0,0,0,0,0,0,0,0,0,0.860511
21,1,4,2015-01-01,AA,19805,14771,1477101,32457,1247802,31703,...,0,0,0,0,0,0,0,0,0,0.857981
22,1,4,2015-01-01,AA,19805,10721,1072102,30721,1289203,32575,...,0,0,0,0,0,0,0,0,0,0.758052
23,1,4,2015-01-01,AA,19805,11298,1129803,30194,1288903,32211,...,0,0,0,0,0,0,0,0,0,0.788558
24,1,4,2015-01-01,AA,19805,12892,1289203,32575,1330303,32467,...,0,0,0,0,0,0,0,0,0,0.796296
26,1,4,2015-01-01,AA,19805,13891,1389101,32575,1129803,30194,...,0,0,0,0,0,0,0,0,0,0.873326
27,1,4,2015-01-01,AA,19805,12892,1289203,32575,1247802,31703,...,0,0,0,0,0,0,0,0,0,0.789763
28,1,4,2015-01-01,AA,19805,12892,1289203,32575,1217302,32134,...,0,0,0,0,0,0,0,0,0,0.698944
29,1,4,2015-01-01,AA,19805,12892,1289203,32575,1247802,31703,...,0,0,0,0,0,0,0,0,0,0.803708
30,1,4,2015-01-01,AA,19805,13830,1383002,33830,1129803,30194,...,0,0,0,0,0,0,0,0,0,0.862216
31,1,4,2015-01-01,AA,19805,12478,1247802,31703,1289203,32575,...,0,0,0,0,0,0,0,0,0,0.846425
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
469938,31,6,2015-01-31,WN,19393,15304,1530402,33195,1412202,30198,...,0,0,0,0,0,0,0,0,0,NaN
469939,31,6,2015-01-31,WN,19393,15304,1530402,33195,1430702,30721,...,0,0,0,0,0,0,0,0,0,NaN
469940,31,6,2015-01-31,WN,19393,15304,1530402,33195,1430702,30721,...,0,0,0,0,0,0,0,0,0,NaN
469941,31,6,2015-01-31,WN,19393,15304,1530402,33195,1449202,34492,...,0,0,0,0,0,0,0,0,0,NaN
469942,31,6,2015-01-31,WN,19393,15304,1530402,33195,1449202,34492,...,0,0,0,0,0,0,0,0,0,NaN
469943,31,6,2015-01-31,WN,19393,15304,1530402,33195,1457604,34576,...,0,0,0,0,0,0,0,0,0,NaN
469944,31,6,2015-01-31,WN,19393,15304,1530402,33195,1473003,33044,...,0,0,0,0,0,0,0,0,0,NaN
469945,31,6,2015-01-31,WN,19393,15304,1530402,33195,1473003,33044,...,0,0,0,0,0,0,0,0,0,NaN
469946,31,6,2015-01-31,WN,19393,15304,1530402,33195,1484304,34819,...,0,0,0,0,0,0,0,0,0,NaN
469947,31,6,2015-01-31,WN,19393,15304,1530402,33195,1501603,31123,...,0,0,0,0,0,0,0,0,0,NaN
469948,31,6,2015-01-31,WN,19393,15304,1530402,33195,1501603,31123,...,0,0,0,0,0,0,0,0,0,NaN
469949,31,6,2015-01-31,WN,19393,15370,1537002,34653,1125903,30194,...,0,0,0,0,0,0,0,0,0,NaN
469950,31,6,2015-01-31,WN,19393,15370,1537002,34653,1125903,30194,...,0,0,0,0,0,0,0,0,0,NaN
469951,31,6,2015-01-31,WN,19393,15370,1537002,34653,1129202,30325,...,0,0,0,0,0,0,0,0,0,NaN
469952,31,6,2015-01-31,WN,19393,15370,1537002,34653,1219102,31453,...,0,0,0,0,0,0,0,0,0,NaN
469953,31,6,2015-01-31,WN,19393,15370,1537002,34653,1288903,32211,...,0,0,0,0,0,0,0,0,0,NaN
469954,31,6,2015-01-31,WN,19393,15370,1537002,34653,1323202,30977,...,0,0,0,0,0,0,0,0,0,NaN
469955,31,6,2015-01-31,WN,19393,15370,1537002,34653,1410702,30466,...,0,0,0,0,0,0,0,0,0,NaN
469956,31,6,2015-01-31,WN,19393,15370,1537002,34653,1501603,31123,...,0,0,0,0,0,0,0,0,0,NaN
469957,31,6,2015-01-31,WN,19393,15376,1537602,30436,1129202,30325,...,0,0,0,0,0,0,0,0,0,NaN
469958,31,6,2015-01-31,WN,19393,15376,1537602,30436,1129202,30325,...,0,0,0,0,0,0,0,0,0,NaN
469959,31,6,2015-01-31,WN,19393,15376,1537602,30436,1288903,32211,...,0,0,0,0,0,0,0,0,0,NaN
469960,31,6,2015-01-31,WN,19393,15376,1537602,30436,1288903,32211,...,0,0,0,0,0,0,0,0,0,NaN
469961,31,6,2015-01-31,WN,19393,15376,1537602,30436,1288903,32211,...,0,0,0,0,0,0,0,0,0,NaN
469962,31,6,2015-01-31,WN,19393,15376,1537602,30436,1288903,32211,...,0,0,0,0,0,0,0,0,0,NaN
469963,31,6,2015-01-31,WN,19393,15376,1537602,30436,1289203,32575,...,0,0,0,0,0,0,0,0,0,NaN
469964,31,6,2015-01-31,WN,19393,15376,1537602,30436,1289203,32575,...,0,0,0,0,0,0,0,0,0,NaN
469965,31,6,2015-01-31,WN,19393,15376,1537602,30436,1289203,32575,...,0,0,0,0,0,0,0,0,0,NaN
469966,31,6,2015-01-31,WN,19393,15376,1537602,30436,1323202,30977,...,0,0,0,0,0,0,0,0,0,NaN
469967,31,6,2015-01-31,WN,19393,15376,1537602,30436,1467903,33570,...,0,0,0,0,0,0,0,0,0,NaN

In [105]:
#test train model